/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSlugIndexImport } from './routes/_layout/$slug/index'
import { Route as LayoutSlugSettingsImport } from './routes/_layout/$slug/settings'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSlugIndexRoute = LayoutSlugIndexImport.update({
  path: '/$slug/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSlugSettingsRoute = LayoutSlugSettingsImport.update({
  path: '/$slug/settings',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$slug/settings': {
      id: '/_layout/$slug/settings'
      path: '/$slug/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof LayoutSlugSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$slug/': {
      id: '/_layout/$slug/'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof LayoutSlugIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSlugSettingsRoute: typeof LayoutSlugSettingsRoute
  LayoutSlugIndexRoute: typeof LayoutSlugIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSlugSettingsRoute: LayoutSlugSettingsRoute,
  LayoutSlugIndexRoute: LayoutSlugIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/$slug/settings': typeof LayoutSlugSettingsRoute
  '/$slug': typeof LayoutSlugIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/$slug/settings': typeof LayoutSlugSettingsRoute
  '/$slug': typeof LayoutSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$slug/settings': typeof LayoutSlugSettingsRoute
  '/_layout/$slug/': typeof LayoutSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/' | '/$slug/settings' | '/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/$slug/settings' | '/$slug'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/'
    | '/_layout/$slug/settings'
    | '/_layout/$slug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/$slug/settings",
        "/_layout/$slug/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/$slug/settings": {
      "filePath": "_layout/$slug/settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/$slug/": {
      "filePath": "_layout/$slug/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
